version: '3.6'

services:
    mssql-server-blahofilm:
        image: mcr.microsoft.com/mssql/server
        environment:
          SA_PASSWORD: YourPassword123
          ACCEPT_EULA: Y
          MSSQL_PID: Express
        ports:
          - "1433:1433"

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.11-management
        ports:
            - "5672:5672"
            - "15672:15672"

    userservice:
        container_name: userservice
        image: userservice
        build:
            context: .
            dockerfile: UserService/UserServiceAPI/Dockerfile
        ports:
            - 7173:8080
        depends_on:
            - mssql-server-blahofilm

    filmservice:
        container_name: filmservice
        image: filmservice
        build:
            context: .
            dockerfile: FilmService/FilmServiceAPI/Dockerfile
        ports:
            - 7174:8080
        depends_on:
            - mssql-server-blahofilm
